
import "./globals.css";
import { Inter, Manrope, IBM_Plex_Sans } from "next/font/google";
import { Space_Grotesk } from "next/font/google";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const manrope = Manrope({ subsets: ["latin"], variable: "--font-manrope" });
const ibmPlexSans = IBM_Plex_Sans({ 
  subsets: ["latin"], 
  variable: "--font-ibm-plex-sans",
  weight: ["400", "500", "600", "700"]
});
const spaceGrotesk = Space_Grotesk({ 
  subsets: ["latin"], 
  variable: "--font-space-grotesk",
  weight: ["400", "500", "600", "700"]
});

export const metadata = {
  title: "Sentinel",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: '/favicon.ico',
        sizes: 'any',
      },
    ],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico?v=3" />
      </head>
      <body className={`${inter.variable} ${manrope.variable} ${ibmPlexSans.variable} ${spaceGrotesk.variable} font-sans antialiased`}>{children}</body>
    </html>
  );
}
