
import "./globals.css";
import { Inter } from "next/font/google";
import { Sora } from "next/font/google";
import { Analytics } from '@vercel/analytics/next';


const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const sora = Sora({ subsets: ["latin"], variable: "--font-sora", weight: ["400", "600", "700"] });

export const metadata = {
  title: "Sentinel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${sora.variable} font-sans antialiased`}>{children}</body>
    </html>
  );
}
